apiVersion: apps/v1
kind: Deployment
metadata:
  name: sidekiq
spec:
  replicas: 1  # Number of Sidekiq workers; adjust based on your needs
  selector:
    matchLabels:
      app: sidekiq
  template:
    metadata:
      labels:
        app: sidekiq
    spec:
      containers:
      - name: sidekiq
        image: ittselali/my-rails-app:latest
        command: ["bundle", "exec", "sidekiq"]
        env:
        - name: RAILS_ENV
          value: "development"  # or "production" depending on your environment
        - name: REDIS_URL
          value: "redis://redis-service:6379/1"  # Ensure this matches your Redis service configuration
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: my-postgres-ha-postgresql-ha-postgresql
              key: password
        - name: DATABASE_PRIMARY_URL
          value: "postgresql://postgres:$(POSTGRES_PASSWORD)@my-postgres-ha-postgresql-ha-postgresql-0.my-postgres-ha-postgresql-ha-postgresql-headless.default.svc.cluster.local:5432/postgres"
        - name: DATABASE_REPLICA_URL
          value: "postgresql://postgres:$(POSTGRES_PASSWORD)@my-postgres-ha-postgresql-ha-pgpool.default.svc.cluster.local:5432/postgres"
        resources:
          requests:
            memory: "500Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
      restartPolicy: Always
